name: ubuntu-clock-app
version: 3.8.480
summary: Ubuntu Clock app
description: The clock app for all Ubuntu devices
confinement: strict
grade: devel

apps:
    ubuntu-clock-app:
        command: desktop-launch $SNAP/bin/ubuntu-clock-app
        plugs: [unity7, platform, opengl, network, network-bind]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform

parts:
    ubuntu-clock-app:
        source: .       
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        build-packages:
            - build-essential
            - cmake
            - gettext
            - intltool
            - ubuntu-touch-sounds
            - suru-icon-theme
            - qml-module-qttest
            - qml-module-qtsysteminfo
            - qml-module-qt-labs-settings
            - qtdeclarative5-u1db1.0
            - qtdeclarative5-qtmultimedia-plugin
            - qtdeclarative5-qtpositioning-plugin
            - qtdeclarative5-ubuntu-content1
            - qt5-default
            - qtbase5-dev
            - qtdeclarative5-dev
            - qtdeclarative5-dev-tools
            - qtdeclarative5-folderlistmodel-plugin
            - qtdeclarative5-ubuntu-ui-toolkit-plugin
            - xvfb

        snap:
            - -usr/share/doc
            - -usr/include
        after: [desktop-ubuntu-app-platform]

    environment:
        source: snap/
        plugin: dump
        organize:
            ubuntu-clock-app.wrapper: bin/ubuntu-clock-app
